name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  http: ^0.12.0+2
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.5.0
  build_test: ^0.10.2
  build_web_compilers: ^1.2.0
  test: ^1.0.0

